---
# tasks file for db-server
- name: Install MariaDB
  yum: 
    name: mariadb-server
    state: present
  notify:
    - Start mariadb

- name: Flush handlers
  meta: flush_handlers

- name: Change mysql root password and keep track in 
  shell: |
    mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('P@ssw0rd'); flush privileges;"
  notify: Restart mariadb

- name: Create Config Mariadb
  shell: |
    printf '[client]
    user=root
    password=P@ssw0rd' > /root/.my.cnf
  args:
    creates: /root/.my.cnf
