---
# tasks file for roles/php-handler
- name: Install Remi 7 repo
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
    state: present

- name: Enable Remi-php73
  shell: yum-config-manager --enable remi-php73

- name: Install php
  yum: 
    name: 
      - php
      - php-common
      - php-opcache
      - php-mcrypt
      - php-cli
#      - php-fpm
      - php-gd
      - php-curl
      - php-mysql
      - php-mbstring
#    enablerepo: remi-php70 
    state: present
  notify: Restart httpd