---
# tasks file for setup-vhosts
- name: Create vhost.d nginx/httpd
  file:
      path: "{{ dir_config }}"
      state: directory
  with_items:
    - /etc/nginx/vhost.d
    - /etc/httpd/vhost.d
  loop_control: 
    loop_var: dir_config

- name: Edit httpd.conf
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      IncludeOptional vhost.d/*.conf
  notify: Restart httpd

- name: Edit config in NGINX
  lineinfile:
    path: /etc/nginx/nginx.conf
    backup: yes
    insertafter: /*include \/etc\/nginx\/conf\.d*/
    line: "    include /etc/nginx/vhost.d/*.conf;"

- name: Change user running nginx to apache
  lineinfile:
    path: /etc/nginx/nginx.conf
    backup: yes
    regexp: '^user nginx;'
    line: "user apache;"
  notify: Restart nginx

- name: Change owner for /var/lib/nginx
  file:
    path: /var/lib/nginx
    owner: apache
    group: root
    recurse: yes

